server:
  port: 8082
  error:
    include-message: always

jwt:
  secret:
  expire: 900000 #15 min

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teste?serverTimezone=UTC
    username: root
    password: 1br2e3n4o5
  jpa:
    show-sql: true

