server:
  port: 8082
  error:
    include-message: always

jwt:
  secret: abc123#%1235$
  expire: 900000 #15 min

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useTimezone=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    show-sql: true