
/* STUDENT TABLE */
CREATE TABLE STUDENT (
     ID DECIMAL(19,2) NOT NULL,
     ADDRESS_ID VARCHAR(255),
     CARD_ID VARCHAR(255),
     CLASS_NAME VARCHAR(255),
     CPF VARCHAR(255),
     NAME VARCHAR(255), PRIMARY KEY (ID)
);

/* ADDRESS TABLE */
CREATE TABLE ADDRESS (
    ID DECIMAL(19,2) NOT NULL,
    CEP VARCHAR(255),
    CITY VARCHAR(255),
    COMPLEMENT VARCHAR(255),
    NEIGHBORHOOD VARCHAR(255),
    NUMBER VARCHAR(255),
    STREET VARCHAR(255),
    UF VARCHAR(255), PRIMARY KEY (ID)
);

/* CARD TABLE */
CREATE TABLE CARD (
    ID DECIMAL(19,2) NOT NULL,
    TOKEN_CARD VARCHAR(255) UNIQUE NOT NULL,
    BRAND VARCHAR(255),
    CVV VARCHAR(255),
    NUMBER VARCHAR(255),
    VALIDATE VARCHAR(255),
    PRIMARY KEY (ID)
);

/* STUDENT TRANSACTION  */
CREATE TABLE STUDENT_TRANSACTION (
    TRANSACTION_ID BIGINT NOT NULL AUTO_INCREMENT,
    STUDENT_ID DECIMAL(19,2) NOT NULL,
    TOKEN_CARD VARCHAR(255) NOT NULL,
    TRANSACTION_CODE_EXTERNAL VARCHAR(255),
    TRANSACTION_DATE DATETIME(6),
    VALUE DECIMAL(19,2),

    PRIMARY KEY (TRANSACTION_ID)
);
